In [13]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

print(type(a))
print(a.shape)
print(a[0, 0], a[1, 0])
a[0, 0] = 7
print(a)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1 4
[[7 2 3]
 [4 5 6]]


In [36]:
import numpy as np

a = np.zeros((2, 2))
print(a)

b = np.ones((2, 3))
print(b)

c = np.eye(4)
print(c)

d = np.full((2, 3),7)
print(d)

e = np.random.random((4, 5))
print(e)

f = np.arange(10)
print(f)


[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.51447994 0.47228025 0.10488494 0.69698654 0.81865637]
 [0.7968043  0.02170243 0.38751323 0.83933386 0.58794631]
 [0.08714524 0.740742   0.66202421 0.10251213 0.45965467]
 [0.3464462  0.54788575 0.07982582 0.78497329 0.15973449]]
[0 1 2 3 4 5 6 7 8 9]


In [44]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

b = a[:2, 1:3]
print(b)

print(a[0, 1])

b[0, 0] = 14
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
[[ 1 14  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [69]:
import numpy as np
 
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

print(a[[0, 0, 1, 2], [1, 0, 1, 1]])
print(np.array([a[0,1], a[0,0], a[1,1], a[2,1]]))

print(a[[0, 0], [1, 1]])
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[2 1 4 6]
[2 1 4 6]
[2 2]
[2 2]


In [79]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1])
print(b)

print(a[np.arange(4), b])

a[np.arange(4), b] +=10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [85]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_exp = a > 2
print(bool_exp)

print(a[bool_exp])
print(a[a > 2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [97]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

y = np.array([[1.0, 2.2], [3.1, 4]])
print(y.dtype)

z = np.array([1, 2], dtype=np.int64)
print(z.dtype)

int64
float64
int64


In [108]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x/y)
print(np.divide(x, y))

print(np.sqrt(x))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [122]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [121]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))

print(np.sum(x, axis=0)) #column
print(np.sum(x, axis=1)) #row

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [123]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [132]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
print(y)

for i in np.arange(4):
    y[i, :] = x[i, :] + v
    
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [135]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [137]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
